### ISSUE TITLE
Tab click waiting for css transition?

### ISSUE THREAD

**Issue by johs** [ermouth/couch-photon#1]
Occationally, first click on top tabs don't work. I see there is a css transition going on and maybe it is linked to that?
To test it, move cursor very quickly in and click.
Tested on MacOS 10.12.5 w/ Chrome, Vivaldi, Safari, Firefox

**Comment by ermouth** [comment]
Ah, pretty interesting. The reason is your cursor is actually still moving at the moment of the click. Since tabs are draggable your action assumed as just started drag, that immediately finishes.

Good catch easy to fix, jQ UI Sortable has the `delay` param http://api.jqueryui.com/sortable/#option-delay, which I definitely forgot to set properly.

**Comment by ermouth** [comment]
Seems I fixed, please update from the repo.
