### ISSUE TITLE
Feature suggestion: Show size of views / One click to compact all views

### ISSUE THREAD

**Issue by SAPikachu** [ermouth/couch-photon#23]
Thanks for your awesome tool! It would be great if size occupied by views can be shown in the UI, this can help us to determine whether we should manually compact views. 

Also for now we have to choose ddoc when we try to compact views, would be great if we have option to compact all ddocs at once.

Thanks again!

**Comment by ermouth** [comment]
@SAPikachu Thank for your proposals, both are great. Hope to add those features soon.

**Comment by ermouth** [comment]
Both features added since 1.10.2, do update. Related commit is https://github.com/ermouth/couch-photon/commit/ab7c1fcc09df25276584a31007e67e12ad0ffa36.

Design docs list now shows brief indices size info in collapsed rows, and full result of '/db/_design/doc/_info` request when row is expanded.

Selecting ddocs in Design docs list does not hide [Compact...] btn, clicking it pre-fills dlg list of ddocs to compact with selected entries. Ddocs which have no views are not included.

**Comment by SAPikachu** [comment]
Great, thank you very much!
